--CREATE NEW DATABASE CALLED DATAWAREHOUSE
CREATE DATABASE Datawarehouse
USE Datawarehouse; 

--CREATE 3 SCHEMAS AS I USED MEDALLION APPROACH
CREATE SCHEMA bronze;

CREATE SCHEMA silver;

CREATE SCHEMA gold;