select * from gold.dim_products
select * from gold.fact_sales
select * from gold.dim_customers


--Explore all countries that our customers come from
SELECT DISTINCT country FROM gold.dim_customers

--Explore all the product categories "The Major Divisions"
SELECT DISTINCT category, sub_category FROM gold.dim_products

--Explore the earliest and latest create date and birth date
SELECT 
	MIN(create_date) as earliest_create_date,
	MAX(create_date) as latest_create_date,
	MIN(birth_date) as earliest_birth_date,
	MAX(birth_date) as latest_birth_date
	from gold.dim_customers

--Find the date of the first and last order
SELECT
	MIN(order_date) as first_order_date,
	MAX(order_date) as last_order_date,
	DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) as total_years,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) as total_months,
	DATEDIFF(DAY, MIN(order_date), MAX(order_date)) as total_days
	FROM gold.fact_sales

--Find the youngest and oldest customer
SELECT
	MIN(birth_date) as oldest_customer,
	DATEDIFF(YEAR,MIN(birth_date),GETDATE()) as oldest_customer_age,
	MAX(birth_date) as youngest_customer,
	DATEDIFF(YEAR,MAX(birth_date),GETDATE()) as youngest_customer_age
	FROM gold.dim_customers

--Find the total sales
SELECT SUM(sales) as total_sales FROM gold.fact_sales

--How many items are sold
SELECT SUM(quantity) as total_quantities from gold.fact_sales

--Find the average selling price
SELECT AVG(price) as average_price FROM gold.fact_sales

--Find the total numbers of orders
SELECT COUNT(DISTINCT order_number) as total_orders FROM gold.fact_sales

--Find the total numbers of products
SELECT COUNT(sales_product_key) as total_orders FROM gold.fact_sales

--Total customets by countries
select
	country,
	count(*) as total_customers
	from gold.dim_customers
	group by country
	order by count(*) Desc

--Total customets by gender
select
	gender,
	count(*) as total_customers
	from gold.dim_customers
	group by gender
	order by count(*) Desc

--Total products by category
select
	category,
	count(*) as total_products
	from gold.dim_products
	group by category
	order by count(*) Desc

--Average cost in each category
select
	category,
	AVG(product_cost) as average_cost
	from gold.dim_products
	group by category
	order by AVG(product_cost) Desc

--total revenue generated for each category
select 
	category,
	sum(sales) as revenue
	from gold.dim_products
	join gold.fact_sales
	on gold.dim_products.product_key = gold.fact_sales.sales_product_key
	group by category
	order by sum(sales) Desc


--total revenue generated by each customer
select
	customer_id,
	first_name,
	last_name,
	sum(sales) as revenue
	from gold.fact_sales
	left join gold.dim_customers
	on gold.dim_customers.customer_id = gold.fact_sales.sales_customer_id
	group by customer_id, first_name, last_name
	order by sum(sales) Desc

--distribution of sold items in countries
select
	country,
	sum(quantity) as sold_items
	from gold.fact_sales
	left join gold.dim_customers
	on gold.dim_customers.customer_id = gold.fact_sales.sales_customer_id
	group by country
	order by sum(quantity) Desc

--which 5 products generates the highest revenue?
select * from (select
	sales_product_key,
	product_number,
	sum(sales) as revenue,
	row_number() over(order by sum(sales) Desc) as rn
	from gold.dim_products
	left join gold.fact_sales
	on gold.dim_products.product_key = gold.fact_sales.sales_product_key
	group by sales_product_key, product_number)k
	where rn<=5

--what are the 5 worst performing products in terms of sales?
select * from(
select 
	sales_product_key,
	product_number,
	sum(sales) as total_sales,
	row_number() over(order by sum(sales)) as rn
	from gold.fact_sales
	left join gold.dim_products
	on gold.dim_products.product_key = gold.fact_sales.sales_product_key
	group by sales_product_key, product_number)t
	where rn<=5

--OR

select top 5
	sales_product_key,
	product_number,
	sum(sales) as total_sales
	from gold.fact_sales
	left join gold.dim_products
	on gold.dim_products.product_key = gold.fact_sales.sales_product_key
	group by sales_product_key, product_number
	order by sum(sales)

--OR
select * from(
select 
	sales_product_key,
	product_number,
	sum(sales) as total_sales,
	DENSE_RANK() over(order by sum(sales)) as rn
	from gold.fact_sales
	left join gold.dim_products
	on gold.dim_products.product_key = gold.fact_sales.sales_product_key
	group by sales_product_key, product_number)t
	where rn<=5

--top 10 customers by revenue
select top 10
	customer_id,
	first_name,
	last_name,
	sum(sales) as revenue
	from gold.fact_sales
	left join gold.dim_customers
	on gold.dim_customers.customer_id = gold.fact_sales.sales_customer_id
	group by customer_id, first_name, last_name
	order by sum(sales) Desc

--the fwest 3 customers by orders
select top 3
	customer_id,
	first_name,
	last_name,
	count(distinct order_number) as total_orders
	from gold.fact_sales
	left join gold.dim_customers
	on gold.fact_sales.sales_customer_id = gold.dim_customers.customer_id
	group by customer_id, first_name, last_name
	order by total_orders

--Exlpore total sales and number of customers based on orders
select
	year(order_date) as years,
	sum(sales) as total_sales,
	count(distinct sales_customer_id) as total_customers,
	sum(quantity) as total_quantities
	from gold.fact_sales
	where year(order_date) is not null
	group by year(order_date)
	order by year(order_date)

--Calculate total sales per month and the cummlatives sales / running total over all years
--Sub-Query
select 
	*,
	sum(total_sales) over(order by Month) as runnning_total
	from(
	select
		DateTrunc(month,order_date) as Month,
		sum(sales) as total_sales
		from gold.fact_sales
		where DateTrunc(month,order_date) is not null
		group by DateTrunc(month,order_date))j
	

--CTE (Common Table Expression)

with CTE as(
select
		DateTrunc(month,order_date) as order_date,
		sum(sales) as total_sales
		from gold.fact_sales
		where DateTrunc(month,order_date) is not null
		group by DateTrunc(month,order_date))
			
			select *,
				sum(total_sales) over(order by order_date) as runnning_total
				from CTE


--Calculate total sales per month and the cummlatives sales / running total over each years individual
--Do this with partition by(year)
with CTE as(
select
		DateTrunc(month,order_date) as order_date,
		sum(sales) as total_sales
		from gold.fact_sales
		where DateTrunc(month,order_date) is not null
		group by DateTrunc(month,order_date))
			
			select *,
				sum(total_sales) over(partition by order_date order by order_date) as runnning_total
				from CTE


--Explore the yearly perfomance of products in terms of total sales

with cte as(
select
	year(f.order_date) as order_year,
	p.product_number as product_name,
	sum(f.sales) as current_sales
	from
	gold.fact_sales f
	left join gold.dim_products p
	on f.sales_product_key = p.product_key
	where f.order_date is not null
	group by year(f.order_date), p.product_number
	)
	select 
		order_year,
		product_name,
		current_sales,
		avg(current_sales) over(partition by product_name) as avg_sales,
		current_sales - avg(current_sales) over(partition by product_name) as avg_diff,
		case when current_sales - avg(current_sales) over(partition by product_name) <0 then 'Below Avg'
		when current_sales - avg(current_sales) over(partition by product_name) >0 then 'Above Avg'
		else 'Avg'
		end as 'avg_change',
		LAG(current_sales) over(partition by product_name order by order_year) as pre_year_sales,
		current_sales - LAG(current_sales) over(partition by product_name order by order_year) as YOY_sales,
		case when current_sales - LAG(current_sales) over(partition by product_name order by order_year) > 0 then 'Increased'
		when current_sales - LAG(current_sales) over(partition by product_name order by order_year) < 0 then 'Decreased'
		else 'No Change'
		end as YOY_change
		from cte
		order by product_name, order_year


--Which categories contribute the most to overall sales?
with cte as(
select 
	p.category,
	sum(f.sales) as overall_sales
	from gold.fact_sales f
	left join gold.dim_products p
	on f.sales_product_key = p.product_key
	group by p.category)

	select
		category,
		overall_sales,
		sum(overall_sales) over() as total_sales,
		concat(round((cast(overall_sales as float)/sum(overall_sales)over())*100,2),'%') as percentage_of_total
		from cte
		order by overall_sales desc


--Data Segmentation
--Segment products into cost ranges and 
--count how many products fall into each segment
with CTE as(
select
	product_id,
	product_number,
	product_cost,
	case when product_cost <100 then 'Below 100'
		 when product_cost between 100 and 500 then '100 - 500'
		 when product_cost between 500 and 1000 then '500 - 1000'
		 else 'Above 1000'
	end as cost_range
	from gold.dim_products)

	select
		cost_range,
		count(*) as total_count
		from CTE
		group by cost_range
		order by count(*) desc;


--customer segmentation:
--VIP: at least 12 month of history and spent > 5000
--Regular: at least 12 month of history and spent 5000 or less
--New: lifespan less than 12 month of history
with CTE as(
select
	c.customer_id,
	concat(c.first_name,' ',c.last_name) as full_name,
	sum(f.sales) as total_spent,
	min(f.order_date) as first_order,
	max(f.order_date) as last_order,
	DATEDIFF(month, min(f.order_date), max(f.order_date)) as total_period,
	case when DATEDIFF(month, min(f.order_date), max(f.order_date)) >= 12 and sum(f.sales)>5000 then 'VIP'
		 when DATEDIFF(month, min(f.order_date), max(f.order_date)) >= 12 and sum(f.sales)<=5000 then 'Regular'
		 else 'New'
	end as customer_type
	from gold.fact_sales f
	left join gold.dim_customers c
	on f.sales_customer_id = c.customer_id
	group by c.customer_id, concat(c.first_name,' ',c.last_name))
		select 
			customer_type,
			count(*) as total_count
			from CTE
			group by customer_type
			order by count(*) desc

